### ISSUE TITLE
Determine whether object is wall or ball through relative velocity

### ISSUE THREAD

**Issue by IfTrueReturnTrue** [IfTrueReturnTrue/EntitledMHSrobot2021#4]
calculate velocity of robot

calculate velocity of object

```python
if relative velocity != robot velocity:
    return True
else:
    return False
```

it'll be something like that. 

@mykales @BlackReaper665 
you two better help

##What this issue involves
- it involves the gyro sensor
- ultrasonic sensor

**Comment by mykales** [comment]
**Ball Detection method (faulty)**
  
  _#Inputs
  #angle = angle between Forward sensor fb and Diagonal sensor
  #Diag sens fb = Diagonal sensor feedback value
  #Forward sens fb = Forward sensor feedback value_
  
  cos(t) = A/H
  
  Cos(angle) = Forward sens fb / Diag sens fb
  Cos(angle) * Diag sens fb = Forward sens fb
  Therefore, 
  If true, then the triangle is true and there must be a wall
  If false, then the triangle is incomplete and there must be a ball
  
  FAULT 1: This is assuming that the wall is perpendicular to the Forward sensor which would make it a right angled triangle. This is usually not the case as the bot will be on an angle compared to the wall, making it not perpendicular and the calculations incorrect.
  
  FAULT 2: Sensor ranges may be too short and lead to exceptions.
  
  Potential Fixes: If the angle of the bot in comparison to starting position can be reached, either using a compass sensor or tracking movements (tracking movements may be affected by external factors moving the bot, ie. another bot; better to use compass sensor), then this may be incorporated into the calculations to be able to calculate all angles in the triangle to be used for completion checking. Fault 2 is currently unfixable due to physical constraints..
  
  **Questions: 
  -Does the compass sensor feedback values in degree integers? If not, what value does it feedback?
  -Is the compass sensor accurate enough to be able to orient itself perpendicular to the wall**
  
  **Revised Potential Method**
  
  #Inputs (above inputs inclusive)
  #Direction = Forward Sensor's relative angle to 0° or starting position (clockwise)
  
  First we need to find all hypothetical angles inside the triangle if it were complete
  x = 3rd angle
  180 = direction + angle + x
  x = 180 - direction - angle
  
  angle x should then be opposite to the line of Diag sens fb. For ease of calculations and interpretation, I will be simplifying all variables to a, b, c, A, B, C. Each letter's corresponding capital/lower case forms are opposite to each other on the triangle.
  
  We will define these angles to corresponding A, B, C.
  A = Angle
  B = x
  C = direction
  
  We will define the side lengths using a, b, c.
  a = sqrt( (Diag sens fb)^2 + (Forward sens fb)^2 )
  b = Diag sens fb
  c = Forward sens fb
  
  Calculations:
  a / sin(A) =  b / sin(B) = c / sin(C)
  b / sin(B)  = c / sin(C)
  c = ( b / sin(B) ) * sin(C)
  
  If the Forward Sensor Feedback is equal to the Diagonal Sensor Feedback divided by the Sine of angle 'x' with both multiplied by the Sine of angle 'direction', then the triangle is complete and there is no obstructions (no ball)
  
  If the Forward Sensor Feedback does not equal this, then there is an obstruction (ball).
  
  
  
  Overall, these calculations are likely incorrect for my second method and likely needs some re-tweaking. Otherwise, all theory _should_  be correct, hopefully. I don't know all the code required to code this yet (such as grabbing angle 'direction'), though it should be pretty straight forward. I wrote this while eating my dinner.
 Please answer my above questions ASAP.

**Comment by IfTrueReturnTrue** [comment]
sheeeeeeeeeeeeeeeeeeeeeeesh

**Comment by IfTrueReturnTrue** [comment]
@mykales 
In response to Potential issue #1, we know that we cannot turn our bots, and the ultrasonic sensor will always be pointing toward the perpendicular direction to the wall. 

I think, at the start of the game the way we are going to detect the ball is move sideways until the ball has been detected.

But great work!
Take into my considerations and make this into code form?

**Comment by IfTrueReturnTrue** [comment]
Also, because you are code contributor, you can simply edit the source code.
